#!/bin/sh

# NEEDS TO BE IN /etc/NetworkManager/dispatcher.d/90-polybar

#echo "$2" >> /home/daniel/.config/polybar/log.txt
case "$2" in
        up)
            bash /home/daniel/.config/polybar/polybar-scripts/network-networkmanager.sh --update
        ;;
        down)
            bash /home/daniel/.config/polybar/polybar-scripts/network-networkmanager.sh --update
        ;;
esac
